# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "887110872f7dd4f2d175308b5bef27aa"
application_url = "https://smart-forecast-prod.suphero.store"
embedded = true
name = "Smart Forecast"
handle = "smart-forecast"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, read_inventory"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

[auth]
redirect_urls = [
  "https://smart-forecast-prod.suphero.store/auth/callback",
]

[pos]
embedded = false

[build]
dev_store_url = "smart-forecast-demo.myshopify.com"
include_config_on_deploy = true
