# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d713d4c7b0fc50d65d4a1554ba059827"
application_url = "https://acids-storm-tourist-adipex.trycloudflare.com"
embedded = true
name = "[DEV] Smart Forecast"
handle = "dev-p-smart-forecast"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, read_inventory, read_locations, read_inventory, write_inventory"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/bulk_operations/finish"
  topics = [ "bulk_operations/finish" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://acids-storm-tourist-adipex.trycloudflare.com/auth/callback",
  "https://acids-storm-tourist-adipex.trycloudflare.com/auth/shopify/callback",
  "https://acids-storm-tourist-adipex.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "smart-forecast-demo.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
