# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d713d4c7b0fc50d65d4a1554ba059827"
application_url = "https://frederick-citysearch-spice-robust.trycloudflare.com"
embedded = true
name = "[DEV] Smart Forecast"
handle = "dev-p-smart-forecast"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, read_customers, read_inventory, read_reports"

[webhooks]
api_version = "2022-07"

  [[webhooks.subscriptions]]
  uri = "https://b01c-176-41-143-213.ngrok.io/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://frederick-citysearch-spice-robust.trycloudflare.com/auth/callback",
  "https://frederick-citysearch-spice-robust.trycloudflare.com/auth/shopify/callback",
  "https://frederick-citysearch-spice-robust.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "smart-forecast-demo.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
