# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "887110872f7dd4f2d175308b5bef27aa"
application_url = "https://fixit-prod.suphero.online"
embedded = true
name = "Smart Forecast"
handle = "smart-forecast"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_all_orders, read_orders, read_inventory, read_locations, write_inventory, read_content"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/bulk_operations/finish"
  topics = [ "bulk_operations/finish" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [
  "https://fixit-prod.suphero.online/auth/callback",
]

[pos]
embedded = false

[build]
dev_store_url = "smart-forecast-demo.myshopify.com"
automatically_update_urls_on_dev = false
include_config_on_deploy = true
