# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e0fa783d50ea44c2bf2dc6297412fc7"
application_url = "https://smart-forecast-test.suphero.store"
embedded = true
name = "[QA] Smart Forecast"
handle = "qa-smart-forecast-1"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, read_inventory"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

[auth]
redirect_urls = [
  "https://smart-forecast-test.suphero.store/auth/callback",
]

[pos]
embedded = false

[build]
dev_store_url = "smart-forecast-demo.myshopify.com"
automatically_update_urls_on_dev = false
include_config_on_deploy = true
