name: Deploy App

on:
  push:
    branches: [ "release", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || 'test' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Packages
        run: npm install -g caprover @shopify/cli@latest

      - name: Deploy with CapRover CLI
        env:
          CAPROVER_URL: ${{ vars.CAPROVER_URL }}
          CAPROVER_APP: ${{ vars.CAPROVER_APP }}
          CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
        run: |
          currentBranch=$(git branch --show-current || echo "master")
          caprover deploy \
            --caproverUrl "$CAPROVER_URL" \
            --appName "$CAPROVER_APP" \
            --appToken "$CAPROVER_APP_TOKEN" \
            --branch "$currentBranch"

      - name: Deploy Shopify
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          CONFIG_FILE: ${{ github.ref_name == 'master' && 'shopify.app.prod.toml' || 'shopify.app.test.toml' }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"
