name: Deploy to CapRover

on:
  push:
    branches: [ "release", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy with CapRover CLI
        env:
          CAPROVER_SERVER: ${{ vars.CAPROVER_SERVER }}
          CAPROVER_APP_NAME: ${{ vars.CAPROVER_APP_NAME }}
          CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
        run: |
          currentBranch=$(git branch --show-current || echo "master")
          caprover deploy \
            --caproverUrl $CAPROVER_SERVER \
            --appName $CAPROVER_APP_NAME \
            --appToken $CAPROVER_APP_TOKEN \
            --branch $currentBranch
